table LeadsAtendimentos
	lineageTag: eb1d279a-5075-4f42-845f-9d9389baf1a5

	column ID_Lead
		dataType: string
		lineageTag: 9cdfadf0-fd61-43c1-bf83-5cf50c19985b
		summarizeBy: none
		sourceColumn: ID_Lead

		annotation SummarizationSetBy = Automatic

	column ID_Paciente
		dataType: string
		lineageTag: c1b2b3c0-e528-45b0-95e4-4bd94b2c71f2
		summarizeBy: none
		sourceColumn: ID_Paciente

		annotation SummarizationSetBy = Automatic

	column ID_Canal
		dataType: string
		lineageTag: 6b38fa65-7458-4aa9-8fe4-bef4c40ee76c
		summarizeBy: none
		sourceColumn: ID_Canal

		annotation SummarizationSetBy = Automatic

	column Data_Contato
		dataType: dateTime
		formatString: Long Date
		lineageTag: a7976649-0872-4377-a5a7-8a48f05cf6e6
		summarizeBy: none
		sourceColumn: Data_Contato

		variation Variation
			isDefault
			relationship: bd9b47d8-2fea-4df3-90ac-b8c0ebba0f54
			defaultHierarchy: LocalDateTable_1dca5c24-3ddb-4396-93d3-e9e9c29edd90.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Status_Funil
		dataType: string
		lineageTag: 9ae959b4-943c-4896-ab82-2d3677a095ed
		summarizeBy: none
		sourceColumn: Status_Funil

		annotation SummarizationSetBy = Automatic

	column Procedimento_Interesse
		dataType: string
		lineageTag: 307ef8f0-5001-4609-a4a8-581c08e420ee
		summarizeBy: none
		sourceColumn: Procedimento_Interesse

		annotation SummarizationSetBy = Automatic

	column 'Valor_Tratamento (R$)'
		dataType: int64
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 8a0900e2-aaab-4491-8011-5f98bfb84ec2
		summarizeBy: sum
		sourceColumn: Valor_Tratamento (R$)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	partition LeadsAtendimentos = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\kamil\Downloads\Geomarketing Clinica MaisOdonto.xlsx"), null, true),
				    LeadsAtendimentos_Sheet = Fonte{[Item="LeadsAtendimentos",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(LeadsAtendimentos_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID_Lead", type text}, {"ID_Paciente", type text}, {"ID_Canal", type text}, {"Data_Contato", type date}, {"Status_Funil", type text}, {"Procedimento_Interesse", type text}, {"Valor_Tratamento (R$)", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

